#!/bin/bash -e

RUNDIR=/run/sentry

GPIO_LOCK=31
GPIO_UNLOCK=30

GPIO_LOCKED=48
GPIO_UNLOCKED=60
GPIO_DOOR=51

###

cmd=$1
gpio=/sys/class/gpio

gpio_export() {
  id=$1; direction=$2; name=$3
  echo $id > $gpio/export
  echo $direction > $gpio/gpio$id/direction
  mkdir -p $RUNDIR
  chown sentry:sentry $gpio/gpio$id/value
  chmod g+w $gpio/gpio$id/value
  ln -sf $gpio/gpio$id/value $RUNDIR/$name
}

gpio_trigger() {
  name=$1
  reset() {
    echo 0 > $RUNDIR/$name
    echo "reset $name signal" 1>&2
  }
  trap reset EXIT
  echo 1 > $RUNDIR/$name
  echo "set $name signal" 1>&2
  sleep 1
}

case $cmd in
init)
  gpio_export $GPIO_LOCK low lock
  gpio_export $GPIO_UNLOCK low unlock
  gpio_export $GPIO_LOCKED in locked
  gpio_export $GPIO_UNLOCKED in unlocked
  gpio_export $GPIO_DOOR in door
  echo "initialized" 1>&2
  ;;
uninit)
  rm $RUNDIR/*
  for id in $GPIO_UNLOCK $GPIO_LOCK $GPIO_UNLOCKED $GPIO_LOCKED $GPIO_DOOR; do
    echo $id > $gpio/unexport
  done
  echo "uninitialized" 1>&2
  ;;
lock|unlock)
  gpio_trigger $cmd
  ;;
locked|unlocked|door)
  cat $RUNDIR/$cmd
  ;;
*)
  echo "usage: $(basename $0) <command>" 1>&2
  echo "  init     Initialize sentry functionality (must be root)" 1>&2
  echo "  uninit   Uninitialize sentry functionality (must be root)" 1>&2
  echo "  lock     Lock the deadbolt" 1>&2
  echo "  unlock   Unlock the deadbolt" 1>&2
  echo "  locked   Is the deadbolt locked? (0|1)" 1>&2
  echo "  unlocked Is the deadbolt unlocked? (0|1)" 1>&2
  echo "  door     Is the door open? (0|1)" 1>&2
  exit 2;
  ;;
esac
