#!/bin/bash

BINDIR=usr/bin
ETCDIR=etc/sentry
CLIENTSDIR=etc/sentry/clients
LIBDIR=usr/lib/sentry

for x in BINDIR ETCDIR CLIENTSDIR LIBDIR VARDIR; do
  install -d "$DESTDIR/${!x}"
done
echo "0 = $0"
SRCDIR=$(dirname "$0")/..
echo "SRCDIR = $SRCDIR"
install -m644 "$SRCDIR/etc/config" "$DESTDIR/$ETCDIR/config"
install -m600 "$SRCDIR/etc/secrets" "$DESTDIR/$ETCDIR/secrets"
install -m644 -t "$DESTDIR/$LIBDIR" "$SRCDIR/lib"/*
install -m755 "$SRCDIR/bin/sentry" "$DESTDIR/$BINDIR/sentry"
